Login into Google Earth


In [ ]:
import ee
ee.__version__

'0.1.310'

In [ ]:
import ee
# Trigger the authentication flow.
ee.Authenticate()

# Initialize the library.
ee.Initialize()

To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

    https://code.earthengine.google.com/client-auth?scopes=https%3A//www.googleapis.com/auth/earthengine%20https%3A//www.googleapis.com/auth/devstorage.full_control&request_id=IVEEAwuFVfOQE9AAOL50FgRN36qt9f6IvlduSHb8U88&tc=5ZtiLgGmg_jupYce5KnNa464mZ0D_Hih0b4RWFBXYXU&cc=8WUBaujsRqvSZztnTsViMCXE5m4-2hWAr_6TsCUeHrY

The authorization workflow will generate a code, which you should paste in the box below. 
Enter verification code: 4/1AX4XfWjEc31UTaQeX3L1biVqgpdHq53km_XTnK-6R0yktRhkETmeyGb3rpw

Successfully saved authorization token.


NDVI

In [ ]:
img = ee.ImageCollection('LANDSAT/LE07/C01/T1_TOA').filterDate('2020-04-01', '2022-08-01')
def NDVI(image):
  return image.expression('float(b("B4") - b("B3")) / (b("B4") + b("B3"))')

ndvi = img.map(NDVI).mean()
print(ndvi.getInfo())
#u_lon = 4.8148
#u_lat = 45.7758
#u_poi = ee.Geometry.Point(u_lon, u_lat)
#scale =0.1
# ndvi = img.normalizedDifference(['sur_refl_b02', 'sur_refl_b01'])
# nd =ndvi.getRegion(u_poi,scale= 0.1).getInfo()
#nd = ndvi.sample(u_poi, scale).first().get('B4').getInfo()

#print('NDVI:', nd)


{'type': 'Image', 'bands': [{'id': 'B4', 'data_type': {'type': 'PixelType', 'precision': 'float'}, 'crs': 'EPSG:4326', 'crs_transform': [1, 0, 0, 0, 1, 0]}]}


EVI

In [ ]:

def EVI(image):
  return image.expression('float(2.5*((b("B4") - b("B3")) / (b("B4") + 6*b("B3")-7.5*b("B1")+1)))')

evi = img.map(EVI).mean()
print(evi.getInfo())
#u_lon = 4.8148
#u_lat = 45.7758
#u_poi = ee.Geometry.Point(u_lon, u_lat)
#scale =0.1
# ndvi = img.normalizedDifference(['sur_refl_b02', 'sur_refl_b01'])
# nd =ndvi.getRegion(u_poi,scale= 0.1).getInfo()
#e = evi.sample(u_poi, scale).first().get('constant').getInfo()

#print('EVI:', e)



{'type': 'Image', 'bands': [{'id': 'constant', 'data_type': {'type': 'PixelType', 'precision': 'float'}, 'crs': 'EPSG:4326', 'crs_transform': [1, 0, 0, 0, 1, 0]}]}


Canopy Height

In [ ]:
from osgeo import gdal

print (gdal.__version__)

2.2.3


In [ ]:
from osgeo import gdal

driver = gdal.GetDriverByName('GTiff')
filename = "/content/drive/MyDrive/IITM/ETH_GlobalCanopyHeight_10m_2020_N30E075_Map.tif" #path to raster
dataset = gdal.Open(filename)
band = dataset.GetRasterBand(1)

cols = dataset.RasterXSize
rows = dataset.RasterYSize

transform = dataset.GetGeoTransform()

xOrigin = transform[0]
yOrigin = transform[3]
pixelWidth = transform[1]
pixelHeight = -transform[5]

data = band.ReadAsArray(0, 0, cols, rows)





In [ ]:
import numpy as np

np.array(data,dtype=object)

In [ ]:
data[0][0]

In [ ]:
d2=data.tolist()

In [ ]:
print(d2)

In [ ]:
d2=data
for row in range(500):
    for col in range(500):
      d2[row][col]=(1,2)

ValueError: ignored

In [ ]:
df2=pd.DataFrame(data)

df2

In [ ]:
df.head(rows+1)

In [ ]:
import pandas as pd
import numpy as np

flat_arr = np. reshape(data, cols*rows)
df=pd.DataFrame(flat_arr)

df.head(rows)

In [ ]:
paramlist=[]

for row in range(rows):
    for col in range(cols):
      lat=col*pixelWidth + xOrigin
      lon=row*pixelHeight + yOrigin
      paramlist.append((lat,lon,data[row][col]))
      if(col%1000==0):
            print(row,col)


In [ ]:


for path in directory:
  dataset = gdal.Open(path)
  band = dataset.GetRasterBand(1)

  cols = dataset.RasterXSize
  rows = dataset.RasterYSize

  transform = dataset.GetGeoTransform()
  xOrigin = transform[0]
  yOrigin = transform[3]
  pixelWidth = transform[1]
  pixelHeight = -transform[5]

  data = band.ReadAsArray(0, 0, cols, rows)

  paramlist=[]
  for row in range(rows):
    for col in range(cols):
      lat=col*pixelWidth + xOrigin
      lon=row*pixelHeight + yOrigin
      poi = ee.Geometry.Point(lat,lon)
      band=value.getRegion(poi,scale= 0.1).getInfo() #terraclimate
      nd = ndvi.sample(poi, scale=0.1).first().get('B4').getInfo() #ndvi
      e = evi.sample(poi, scale=0.1).first().get('constant').getInfo() #evi
      tmmx=band[1][4]*0.1
      tmmn=band[1][5]*0.1
      pet=band[1][6]*0.1
      aet=band[1][7]*0.1
      pr=band[1][8]
      p_pet=pr-pet paramlist=[]
  for row in range(rows):
    for col in range(cols):
      lat=col*pixelWidth + xOrigin
      lon=row*pixelHeight + yOrigin
      poi = ee.Geometry.Point(lat,lon)
      band=value.getRegion(poi,scale= 0.1).getInfo() #terraclimate
      nd = ndvi.sample(poi, scale=0.1).first().get('B4').getInfo() #ndvi
      e = evi.sample(poi, scale=0.1).first().get('constant').getInfo() #evi
      tmmx=band[1][4]*0.1
      tmmn=band[1][5]*0.1
      pet=band[1][6]*0.1
      aet=band[1][7]*0.1
      pr=band[1][8]
      p_pet=pr-pet
      p_aet=pr-aet

      paramlist.append((lat,lon,data[row][col],tmmx,tmmn,pet,aet,pr,p_pet,p_aet,nd,e))

      p_aet=pr-aet

      paramlist.append((lat,lon,data[row][col],tmmx,tmmn,pet,aet,pr,p_pet,p_aet,nd,e))

    df = pd.DataFrame(paramlist,columns=['lat','long','height','tmmx','tmmn','pet','aet','pr','p_pet','p_aet','ndvi','evi'])
    df.export('path')







Other Param from Terra Climate

In [ ]:
dataset = ee.ImageCollection('IDAHO_EPSCOR/TERRACLIMATE').filter(ee.Filter.date('2020-04-01', '2020-08-01'))
value=dataset.select('tmmx','tmmn','pet','aet','pr')

#u_poi = ee.Geometry.Point(u_lon, u_lat)
#tmm = value.getRegion(geometry=u_poi,scale= 0.1)
#bounds = ee.Geometry.Polygon(
#    [[[75,30],
 #     [75+1000*p,30],
  #    [75+1000*p,30+1000*p],
   #   [75,30+1000*p]]])

yo

In [ ]:
p=8.333333333333333e-05


In [ ]:
(3)/p

36000.0

In [ ]:
poi = ee.Geometry.Point([75,33])

l8=ee.ImageCollection('IDAHO_EPSCOR/TERRACLIMATE').filter(ee.Filter.date('2020-04-01', '2020-08-01')).filterBounds(poi)

first = ee.Image(l8.first()).clip(poi)


#value=first.select('tmmx','tmmn','pet','aet','pr').getInfo()

print(first.get('tmmx').getInfo())
#band=value.getRegion(poi,scale= 0.1).getInfo()

None


In [ ]:

bounds = ee.Geometry.Point([75,33])

l8=ee.ImageCollection('IDAHO_EPSCOR/TERRACLIMATE').filter(ee.Filter.date('2020-04-01', '2020-08-01')).filterBounds(bounds)

first = ee.Image(l8.first()).clip(bounds)

proj = first.select([0]).projection()

latlon = ee.Image.pixelLonLat().reproject(proj)

coords = latlon.select(['longitude', 'latitude']).reduceRegion(ee.Reducer.toList(),bounds,0.1)


#lat = ee.List(coords.get('latitude')),getInfo()
#lon = ee.List(coords.get('longitude'))

SP_latitude = ee.Number(coords.get('latitude')).getInfo()
SP_longitude = ee.Number(coords.get('longitude')).getInfo()
print(SP_latitude)
print(SP_longitude)


[33.020833333333336]
[74.97916666666666]


In [ ]:
print((75-75.0625)/p)
print((33-32.97916666666667)/p)


-750.0
249.99999999994316


In [ ]:
30.020833333333336 30.020833333333336 75.02083333333333  32.97916666666667 33.020833333333336
75.02083333333331 74.97916666666666 30.020833333333314   74.97916666666666 74.97916666666666

In [ ]:
(30.0625-30.020833333333336)/p


499.9999999999716

In [ ]:
roi = ee.Geometry.BBox(75, 30, 75+500*p, 30+500*p);
lists=value.getRegion(roi,scale=25000*p).getInfo()
df=pd.DataFrame(lists)
print(df.head(40))

EEException: ignored

In [ ]:
point = ee.Geometry.Point([75, 30])
image = ee.Image('LANDSAT/LC08/C01/T1_SR/LC08_121034_20200314')

image = image.addBands(ee.Image.pixelLonLat())


pointPixel = image.reduceRegion(ee.Reducer.first(),point)
#print(pointPixel,'pointPixel')

SP_latitude = ee.Number(pointPixel.get('latitude')).getInfo()
SP_longitude = ee.Number(pointPixel.get('longitude')).getInfo()
print(SP_latitude)
print(SP_longitude)

30.054906296889065
75.24404410298918


In [ ]:
75.00000036385784 358, 179, 1546, 35, 4 75.24425975242046

30.00000023537466


75.04174956668729

In [ ]:
print((75.00008300886397-75.00000036385784)/0.9917400735730553)

8.333333333333333e-05


In [ ]:
p=8.333333333333333e-05

Dataset Creation

In [ ]:
paramlist=[]

for row in range(5):
  for col in range(5):
    lat=col*pixelWidth + xOrigin
    lon=row*pixelHeight + yOrigin
    poi = ee.Geometry.Point(lat,lon)
    band=value.getRegion(poi,scale= 0.1).getInfo()
    nd = ndvi.sample(poi, scale=0.1).first().get('B4').getInfo()
    e = evi.sample(poi, scale=0.1).first().get('constant').getInfo()
    tmmx=band[1][4]*0.1
    tmmn=band[1][5]*0.1
    pet=band[1][6]*0.1
    aet=band[1][7]*0.1
    pr=band[1][8]
    p_pet=pr-pet
    p_aet=pr-aet

    paramlist.append((lat,lon,data[row][col],tmmx,tmmn,pet,aet,pr,p_pet,p_aet,nd,e))


print(paramlist)



[(75.0, 33.0, 24, 26.5, 14.600000000000001, 109.7, 89.0, 56, -53.7, -33.0, 0.3562164306640625, 0.33509913086891174), (75.00008333333334, 33.0, 25, 26.5, 14.600000000000001, 109.7, 89.0, 56, -53.7, -33.0, 0.3562164306640625, 0.33509913086891174), (75.00016666666667, 33.0, 25, 26.5, 14.600000000000001, 109.7, 89.0, 56, -53.7, -33.0, 0.3562164306640625, 0.33509913086891174), (75.00025, 33.0, 27, 26.5, 14.600000000000001, 109.7, 89.0, 56, -53.7, -33.0, 0.3562164306640625, 0.33509913086891174), (75.00033333333333, 33.0, 27, 26.5, 14.600000000000001, 109.7, 89.0, 56, -53.7, -33.0, 0.3272233009338379, 0.28612008690834045), (75.0, 33.000083333333336, 25, 22.5, 12.100000000000001, 99.10000000000001, 99.10000000000001, 105, 5.8999999999999915, 5.8999999999999915, 0.3562164306640625, 0.33509913086891174), (75.00008333333334, 33.000083333333336, 25, 22.5, 12.100000000000001, 99.10000000000001, 99.10000000000001, 105, 5.8999999999999915, 5.8999999999999915, 0.3562164306640625, 0.33509913086891174),

In [ ]:
import pandas as pd

df = pd.DataFrame(paramlist,columns=['lat','long','height','tmmx','tmmn','pet','aet','pr','p_pet','p_aet','ndvi','evi'])

df

lat       long  height  tmmx  tmmn    pet   aet   pr  p_pet  p_aet  \
0   75.000000  33.000000      24  26.5  14.6  109.7  89.0   56  -53.7  -33.0   
1   75.000083  33.000000      25  26.5  14.6  109.7  89.0   56  -53.7  -33.0   
2   75.000167  33.000000      25  26.5  14.6  109.7  89.0   56  -53.7  -33.0   
3   75.000250  33.000000      27  26.5  14.6  109.7  89.0   56  -53.7  -33.0   
4   75.000333  33.000000      27  26.5  14.6  109.7  89.0   56  -53.7  -33.0   
5   75.000000  33.000083      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
6   75.000083  33.000083      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
7   75.000167  33.000083      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
8   75.000250  33.000083      27  22.5  12.1   99.1  99.1  105    5.9    5.9   
9   75.000333  33.000083      27  22.5  12.1   99.1  99.1  105    5.9    5.9   
10  75.000000  33.000167      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
11  75.000083  33.000167      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
12  75.000167  33.000167      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
13  75.000250  33.000167      27  22.5  12.1   99.1  99.1  105    5.9    5.9   
14  75.000333  33.000167      27  22.5  12.1   99.1  99.1  105    5.9    5.9   
15  75.000000  33.000250      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
16  75.000083  33.000250      26  22.5  12.1   99.1  99.1  105    5.9    5.9   
17  75.000167  33.000250      26  22.5  12.1   99.1  99.1  105    5.9    5.9   
18  75.000250  33.000250      28  22.5  12.1   99.1  99.1  105    5.9    5.9   
19  75.000333  33.000250      28  22.5  12.1   99.1  99.1  105    5.9    5.9   
20  75.000000  33.000333      25  22.5  12.1   99.1  99.1  105    5.9    5.9   
21  75.000083  33.000333      26  22.5  12.1   99.1  99.1  105    5.9    5.9   
22  75.000167  33.000333      26  22.5  12.1   99.1  99.1  105    5.9    5.9   
23  75.000250  33.000333      28  22.5  12.1   99.1  99.1  105    5.9    5.9   
24  75.000333  33.000333      28  22.5  12.1   99.1  99.1  105    5.9    5.9   

        ndvi       evi  
0   0.356216  0.335099  
1   0.356216  0.335099  
2   0.356216  0.335099  
3   0.356216  0.335099  
4   0.327223  0.286120  
5   0.356216  0.335099  
6   0.356216  0.335099  
7   0.356216  0.335099  
8   0.356216  0.335099  
9   0.327223  0.286120  
10  0.356216  0.335099  
11  0.356216  0.335099  
12  0.356216  0.335099  
13  0.356216  0.335099  
14  0.327223  0.286120  
15  0.356216  0.335099  
16  0.356216  0.335099  
17  0.356216  0.335099  
18  0.356216  0.335099  
19  0.327223  0.286120  
20  0.344602  0.318430  
21  0.344602  0.318430  
22  0.344602  0.318430  
23  0.344602  0.318430  
24  0.338391  0.304924

In [ ]:

points_list = [ (355278.165927, 4473095.13829), (355978.319525, 4472871.11636) ] #list of X,Y coordinates

for point in points_list:
    col = int((point[0] - xOrigin) / pixelWidth)
    row = int((yOrigin-point[1]) / pixelHeight)

    print(row)
    print(col)
    print(data[row][col])

[[24 25 25 ...  2  2  2]
 [25 25 25 ...  2  2  2]
 [25 25 25 ...  2  2  2]
 ...
 [ 0  0  0 ... 14 14 14]
 [ 0  0  0 ... 14 14 14]
 [ 0  0  0 ... 15 15 15]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
col=499
row=1

paramlist=[]

lon=col*pixelWidth + xOrigin
lat=row*pixelHeight + yOrigin

poi = ee.Geometry.Point(lon,lat)
band=value.getRegion(poi,scale= 0.1).getInfo() #terraclimate
#nd = ndvi.sample(poi, scale=0.1).first().get('B4').getInfo() #ndvi
#e = evi.sample(poi, scale=0.1).first().get('constant').getInfo() #evi
tmmx=band[1][4]*0.1
tmmn=band[1][5]*0.1
pet=band[1][6]*0.1
aet=band[1][7]*0.1
pr=band[1][8]
p_pet=pr-pet
p_aet=pr-aet

print((lon,lat,row,col,tmmx,tmmn,pet,aet,pr,p_pet,p_aet))




(75.04158333333334, 33.000083333333336, 1, 499, 22.5, 12.100000000000001, 99.10000000000001, 99.10000000000001, 105, 5.8999999999999915, 5.8999999999999915)


In [ ]:
0, 0, 26.5, 14.600000000000001, 109.7, 89.0, 56, -53.7, -33.0)
0, 499, 26.5, 14.600000000000001
0, 500, 26.1, 14.3, 106.9, 90.2, 65, -41.900000000000006, -25.200000000000003)

1, 0, 22.5, 12.100000000000001, 99.10000000000001, 99.10000000000001, 105, 5.8999999999999915, 5.8999999999999915)
 1, 499, 22.5
500, 0, 22.3, 12.0, 97.80000000000001, 97.80000000000001, 109,

1, 1, 22.5, 12.100000000000001
1, 500, 22.0, 11.8,



In [ ]:
d =[[2.2,44,5,3,3,4],[3,34,3,3,3,4]]

In [ ]:
d[1][1] = [d[1][1],2,4]

In [ ]:
print(d)

[[2.2, 44, 5, 3, 3, 4], [3, [34, 2, 4], 3, 3, 3, 4]]


In [ ]:
p=pixelHeight


8.333333333333333e-05

In [ ]:
def getList(lon,lat):

    paramlist=[]
    poi = ee.Geometry.Point(lon,lat)
    band=value.getRegion(poi,scale= 0.1).getInfo()
    tmmx=band[1][4]*0.1
    tmmn=band[1][5]*0.1
    pet=band[1][6]*0.1
    aet=band[1][7]*0.1
    pr=band[1][8]
    p_pet=pr-pet
    p_aet=pr-aet

    paramlist.append((tmmx,tmmn,pet,aet,pr,p_pet,p_aet))

    return paramlist




In [ ]:
def fill(xul,yul,paramlist):

  for row in range(yul,yul+1):
    for col in range(xul,xul+1):
      paramlist.append(d2[row][col])
      d2[row][col]=paramlist

In [ ]:
paramlist=[]
p=pixelHeight

for i in range(0,36000,500):
  for j in range(0,36000,500):

    lon=i*p + xOrigin +15*p
    lat=j*p + yOrigin +15*p

    paramlist=getList(lon,lat)
    fill(i,j,paramlist)
    print(i,j)



In [ ]:
import numpy as np

matrix=np.zeros((72,72,10))

matrix

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:

i=1

for row in range(72):
  for col in range(72):
    matrix[row][col]=[i,i,i,i,i,i,i,i,i,i]
    i=i+1




In [ ]:
matrix[71][71]

array([5184., 5184., 5184., 5184., 5184., 5184., 5184., 5184., 5184.,
       5184.])

In [ ]:
matrix.reshape((72*72),-1)

array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [2.000e+00, 2.000e+00, 2.000e+00, ..., 2.000e+00, 2.000e+00,
        2.000e+00],
       [3.000e+00, 3.000e+00, 3.000e+00, ..., 3.000e+00, 3.000e+00,
        3.000e+00],
       ...,
       [5.182e+03, 5.182e+03, 5.182e+03, ..., 5.182e+03, 5.182e+03,
        5.182e+03],
       [5.183e+03, 5.183e+03, 5.183e+03, ..., 5.183e+03, 5.183e+03,
        5.183e+03],
       [5.184e+03, 5.184e+03, 5.184e+03, ..., 5.184e+03, 5.184e+03,
        5.184e+03]])

In [ ]:
import pandas as pd

df=pd.DataFrame(matrix.reshape((72*72),-1),columns=['a','b','c','d','e','f','g','h','j','k'])

In [ ]:
df.head(80)

a     b     c     d     e     f     g     h     j     k
0    1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
1    2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0   2.0
2    3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0   3.0
3    4.0   4.0   4.0   4.0   4.0   4.0   4.0   4.0   4.0   4.0
4    5.0   5.0   5.0   5.0   5.0   5.0   5.0   5.0   5.0   5.0
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
75  76.0  76.0  76.0  76.0  76.0  76.0  76.0  76.0  76.0  76.0
76  77.0  77.0  77.0  77.0  77.0  77.0  77.0  77.0  77.0  77.0
77  78.0  78.0  78.0  78.0  78.0  78.0  78.0  78.0  78.0  78.0
78  79.0  79.0  79.0  79.0  79.0  79.0  79.0  79.0  79.0  79.0
79  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0  80.0

[80 rows x 10 columns]

In [ ]:
df=pd.read_csv('/content/canopy height name.csv')

In [ ]:
df

Name
0       ETH_GlobalCanopyHeight_10m_2020_N00E006_Map.tif
1     ETH_GlobalCanopyHeight_10m_2020_N00E006_Map_SD...
2       ETH_GlobalCanopyHeight_10m_2020_N00E009_Map.tif
3     ETH_GlobalCanopyHeight_10m_2020_N00E009_Map_SD...
4       ETH_GlobalCanopyHeight_10m_2020_N00E012_Map.tif
...                                                 ...
5297  ETH_GlobalCanopyHeight_10m_2020_S57W075_Map_SD...
5298    ETH_GlobalCanopyHeight_10m_2020_S60W027_Map.tif
5299  ETH_GlobalCanopyHeight_10m_2020_S60W027_Map_SD...
5300    ETH_GlobalCanopyHeight_10m_2020_S60W030_Map.tif
5301  ETH_GlobalCanopyHeight_10m_2020_S60W030_Map_SD...

[5302 rows x 1 columns]

In [ ]:
df.shape

(5302, 1)

In [ ]:
discard = ["SD"]

# drop rows that contain the partial string "Sci"
df=df[~df.Name.str.contains('|'.join(discard))]

#displaydf.Name.str.contains('|'.join(discard))






KeyError: ignored

In [ ]:
df.reset_index(drop=True, inplace=True)

df

Name
0     ETH_GlobalCanopyHeight_10m_2020_N00E006_Map.tif
1     ETH_GlobalCanopyHeight_10m_2020_N00E009_Map.tif
2     ETH_GlobalCanopyHeight_10m_2020_N00E012_Map.tif
3     ETH_GlobalCanopyHeight_10m_2020_N00E015_Map.tif
4     ETH_GlobalCanopyHeight_10m_2020_N00E018_Map.tif
...                                               ...
2646  ETH_GlobalCanopyHeight_10m_2020_S57W069_Map.tif
2647  ETH_GlobalCanopyHeight_10m_2020_S57W072_Map.tif
2648  ETH_GlobalCanopyHeight_10m_2020_S57W075_Map.tif
2649  ETH_GlobalCanopyHeight_10m_2020_S60W027_Map.tif
2650  ETH_GlobalCanopyHeight_10m_2020_S60W030_Map.tif

[2651 rows x 1 columns]

In [ ]:
df.to_csv('list.csv')

In [ ]:
!pip install wget
import wget

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9675 sha256=c11f00924b069fd87984020b5a98b8012df603612f3fbe18919d1283d5ecae56
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget


In [ ]:
for index, row in df[10:12].iterrows():
    print (row["Name"])
    url='https://share.phys.ethz.ch/~pf/nlangdata/ETH_GlobalCanopyHeight_10m_2020_version1/3deg_cogs/'+row["Name"]
    response = wget.download(url,'/content/aloo/'+ row["Name"])


ETH_GlobalCanopyHeight_10m_2020_N00E036_Map.tif


FileNotFoundError: ignored

In [ ]:
df[10:]

Name
10  ETH_GlobalCanopyHeight_10m_2020_N00E036_Map.tif
11  ETH_GlobalCanopyHeight_10m_2020_N00E039_Map.tif
12  ETH_GlobalCanopyHeight_10m_2020_N00E042_Map.tif
13  ETH_GlobalCanopyHeight_10m_2020_N00E045_Map.tif
14  ETH_GlobalCanopyHeight_10m_2020_N00E072_Map.tif
15  ETH_GlobalCanopyHeight_10m_2020_N00E093_Map.tif
16  ETH_GlobalCanopyHeight_10m_2020_N00E096_Map.tif
17  ETH_GlobalCanopyHeight_10m_2020_N00E099_Map.tif
18  ETH_GlobalCanopyHeight_10m_2020_N00E102_Map.tif
19  ETH_GlobalCanopyHeight_10m_2020_N00E105_Map.tif

In [ ]:
s='ETH_GlobalCanopyHeight_10m_2020_N00E036_Map.tif'

In [ ]:
print(s[32:39]+'.csv')

N00E036.csv


In [ ]:
!pip install tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from tqdm import tqdm
import time

for i in tqdm (range (100), desc="Loading..."):
  for j in range(72):
    print(i,j)
    #time.sleep(0.01)

Loading...:  15%|█▌        | 15/100 [00:00<00:00, 140.38it/s]

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
0 20
0 21
0 22
0 23
0 24
0 25
0 26
0 27
0 28
0 29
0 30
0 31
0 32
0 33
0 34
0 35
0 36
0 37
0 38
0 39
0 40
0 41
0 42
0 43
0 44
0 45
0 46
0 47
0 48
0 49
0 50
0 51
0 52
0 53
0 54
0 55
0 56
0 57
0 58
0 59
0 60
0 61
0 62
0 63
0 64
0 65
0 66
0 67
0 68
0 69
0 70
0 71
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
1 29
1 30
1 31
1 32
1 33
1 34
1 35
1 36
1 37
1 38
1 39
1 40
1 41
1 42
1 43
1 44
1 45
1 46
1 47
1 48
1 49
1 50
1 51
1 52
1 53
1 54
1 55
1 56
1 57
1 58
1 59
1 60
1 61
1 62
1 63
1 64
1 65
1 66
1 67
1 68
1 69
1 70
1 71
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13
2 14
2 15
2 16
2 17
2 18
2 19
2 20
2 21
2 22
2 23
2 24
2 25
2 26
2 27
2 28
2 29
2 30
2 31
2 32
2 33
2 34
2 35
2 36
2 37
2 38
2 39
2 40
2 41
2 42
2 43
2 44
2 45
2 46
2 47
2 48
2 49
2 50
2 51
2 52
2 53
2 54
2 55
2 56
2 57
2 58
2 59
2 60
2 61


Loading...:  43%|████▎     | 43/100 [00:00<00:00, 123.00it/s]

 57
25 58
25 59
25 60
25 61
25 62
25 63
25 64
25 65
25 66
25 67
25 68
25 69
25 70
25 71
26 0
26 1
26 2
26 3
26 4
26 5
26 6
26 7
26 8
26 9
26 10
26 11
26 12
26 13
26 14
26 15
26 16
26 17
26 18
26 19
26 20
26 21
26 22
26 23
26 24
26 25
26 26
26 27
26 28
26 29
26 30
26 31
26 32
26 33
26 34
26 35
26 36
26 37
26 38
26 39
26 40
26 41
26 42
26 43
26 44
26 45
26 46
26 47
26 48
26 49
26 50
26 51
26 52
26 53
26 54
26 55
26 56
26 57
26 58
26 59
26 60
26 61
26 62
26 63
26 64
26 65
26 66
26 67
26 68
26 69
26 70
26 71
27 0
27 1
27 2
27 3
27 4
27 5
27 6
27 7
27 8
27 9
27 10
27 11
27 12
27 13
27 14
27 15
27 16
27 17
27 18
27 19
27 20
27 21
27 22
27 23
27 24
27 25
27 26
27 27
27 28
27 29
27 30
27 31
27 32
27 33
27 34
27 35
27 36
27 37
27 38
27 39
27 40
27 41
27 42
27 43
27 44
27 45
27 46
27 47
27 48
27 49
27 50
27 51
27 52
27 53
27 54
27 55
27 56
27 57
27 58
27 59
27 60
27 61
27 62
27 63
27 64
27 65
27 66
27 67
27 68
27 69
27 70
27 71
28 0
28 1
28 2
28 3
28 4
28 5
28 6
28 7
28 8
28 9
28 10
28 11
28 12


Loading...:  68%|██████▊   | 68/100 [00:00<00:00, 111.12it/s]

 0
51 1
51 2
51 3
51 4
51 5
51 6
51 7
51 8
51 9
51 10
51 11
51 12
51 13
51 14
51 15
51 16
51 17
51 18
51 19
51 20
51 21
51 22
51 23
51 24
51 25
51 26
51 27
51 28
51 29
51 30
51 31
51 32
51 33
51 34
51 35
51 36
51 37
51 38
51 39
51 40
51 41
51 42
51 43
51 44
51 45
51 46
51 47
51 48
51 49
51 50
51 51
51 52
51 53
51 54
51 55
51 56
51 57
51 58
51 59
51 60
51 61
51 62
51 63
51 64
51 65
51 66
51 67
51 68
51 69
51 70
51 71
52 0
52 1
52 2
52 3
52 4
52 5
52 6
52 7
52 8
52 9
52 10
52 11
52 12
52 13
52 14
52 15
52 16
52 17
52 18
52 19
52 20
52 21
52 22
52 23
52 24
52 25
52 26
52 27
52 28
52 29
52 30
52 31
52 32
52 33
52 34
52 35
52 36
52 37
52 38
52 39
52 40
52 41
52 42
52 43
52 44
52 45
52 46
52 47
52 48
52 49
52 50
52 51
52 52
52 53
52 54
52 55
52 56
52 57
52 58
52 59
52 60
52 61
52 62
52 63
52 64
52 65
52 66
52 67
52 68
52 69
52 70
52 71
53 0
53 1
53 2
53 3
53 4
53 5
53 6
53 7
53 8
53 9
53 10
53 11
53 12
53 13
53 14
53 15
53 16
53 17
53 18
53 19
53 20
53 21
53 22
53 23
53 24
53 25
53 26
53 27


Loading...: 100%|██████████| 100/100 [00:01<00:00, 84.85it/s]

 43
79 44
79 45
79 46
79 47
79 48
79 49
79 50
79 51
79 52
79 53
79 54
79 55
79 56
79 57
79 58
79 59
79 60
79 61
79 62
79 63
79 64
79 65
79 66
79 67
79 68
79 69
79 70
79 71
80 0
80 1
80 2
80 3
80 4
80 5
80 6
80 7
80 8
80 9
80 10
80 11
80 12
80 13
80 14
80 15
80 16
80 17
80 18
80 19
80 20
80 21
80 22
80 23
80 24
80 25
80 26
80 27
80 28
80 29
80 30
80 31
80 32
80 33
80 34
80 35
80 36
80 37
80 38
80 39
80 40
80 41
80 42
80 43
80 44
80 45
80 46
80 47
80 48
80 49
80 50
80 51
80 52
80 53
80 54
80 55
80 56
80 57
80 58
80 59
80 60
80 61
80 62
80 63
80 64
80 65
80 66
80 67
80 68
80 69
80 70
80 71
81 0
81 1
81 2
81 3
81 4
81 5
81 6
81 7
81 8
81 9
81 10
81 11
81 12
81 13
81 14
81 15
81 16
81 17
81 18
81 19
81 20
81 21
81 22
81 23
81 24
81 25
81 26
81 27
81 28
81 29
81 30
81 31
81 32
81 33
81 34
81 35
81 36
81 37
81 38
81 39
81 40
81 41
81 42
81 43
81 44
81 45
81 46
81 47
81 48
81 49
81 50
81 51
81 52
81 53
81 54
81 55
81 56
81 57
81 58
81 59
81 60
81 61
81 62
81 63
81 64
81 65
81 66
81 67
81 68
81

In [ ]:

import time
import progressbar

widgets = [' [',
         progressbar.Timer(format= 'elapsed time: %(elapsed)s'),
         '] ',
           progressbar.Bar('*'),' (',
           progressbar.ETA(), ') ',
          ]

bar = progressbar.ProgressBar(max_value=36000,
                              widgets=widgets).start()

for i in range(100):
    time.sleep(0.001)
    bar.update(i)

 [elapsed time: 0:00:00] |                                  | (ETA:   0:00:45) 